### ISSUE TITLE
Improve measurement with TSC

### ISSUE THREAD

**Issue by Max-Meldrum** [joelonsql/rust-timeit#1]
Consider using something like [minstant](https://github.com/tikv/minstant?tab=readme-ov-file) to get more accurate measurement when TSC is available.

**Comment by joelonsql** [comment]
Thanks Max for the great suggestion! Clearly an improvement, much less noise.

`use std::time::Instant;`

![half_karatsuba-std-time-intel-i9](https://github.com/joelonsql/rust-timeit/assets/1784776/6e4f6566-071e-486b-83a0-b0a90d57e3f1)

vs

`use minstant::Instant;`

![image](https://github.com/joelonsql/rust-timeit/assets/1784776/91b8bd5a-5e8b-4671-ad77-4970fd3af89a)
